spring:
  datasource:
    url: jdbc:${DB_DRIVER:postgresql}://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:explorer_db}?currentSchema=${DB_SCHEMA:network_monitoring_agg}
    username: ${DB_USER:cardano}
    password: ${DB_PASSWORD:ch@ng3m3}
  flyway:
    locations:
      - classpath:db/store/{vendor}
      - classpath:db/store/explorer_db
    out-of-order: 'true'
  application:
    name: cf-network-monitoring-aggregator
  jpa:
    hibernate:
      ddl-auto: update

apiPrefix: /api/v1

server:
  port: '8080'

store:
  cardano:
    protocol-magic: 764824073
    host: backbone.mainnet.cardanofoundation.org
    port: 3001
    sync-start-slot: 135707748
    sync-start-blockhash: 561f9b9865df6c3cbb8996de409a4de3b7f3ea9c906b9f616647e22d8a3f9866
  blocks:
    epoch-calculation-interval=14400:

aggregation:
  transaction-adoption:
    enabled: true
    wallets: ""
  transaction-adoption-6h:
    enabled: false
    wallets: ""

---
spring:
  config:
    activate:
      on-profile: preprod

network: preprod

store:
  cardano:
    protocol-magic: 1
    port: 30000
    host: preprod-node.world.dev.cardano.org

